### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by busslina** [GregoryConrad/rearch-dart#135]
I just changed my `use.rawValueWrapper`'s to `use.data`'s and I got an error the first time I access my side effect.

Error:
```
Apr 13 16:29:43 server3.busslina.com bash[135558]: Unhandled exception:
Apr 13 16:29:43 server3.busslina.com bash[135558]: Concurrent modification during iteration: Instance of 'MappedListIterable<() => _CapsuleManager?, _CapsuleManager?>'.
Apr 13 16:29:43 server3.busslina.com bash[135558]: #0      ListIterator.moveNext (dart:_internal/iterable.dart:348)
Apr 13 16:29:43 server3.busslina.com bash[135558]: #1      NonNullsIterator.moveNext (dart:_internal/iterable.dart:921)
Apr 13 16:29:43 server3.busslina.com bash[135558]: #2      SetBase.addAll (dart:collection/set.dart:58)
Apr 13 16:29:43 server3.busslina.com bash[135558]: #3      _Set.addAll (dart:collection-patch/compact_hash.dart:986)
Apr 13 16:29:43 server3.busslina.com bash[135558]: #4      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:192)
Apr 13 16:29:43 server3.busslina.com bash[135558]: #5      Iterable.toSet (dart:core/iterable.dart:512)
Apr 13 16:29:43 server3.busslina.com bash[135558]: #6      CapsuleContainer.runTransaction (package:rearch/rearch.dart:136)
Apr 13 16:29:43 server3.busslina.com bash[135558]: #7      _CapsuleManager.rebuild (package:rearch/src/impl.dart:89)
Apr 13 16:29:43 server3.busslina.com bash[135558]: #8      SideEffectRegistrarExtension.cachedSerializableValue.<anonymous closure> (package:busslina_dart_lightweight_lib/core/extensions/side_effects.rearch.extension.dart:51)
Apr 13 16:29:43 server3.busslina.com bash[135558]: #9      SecurityModule._checkAndLoadSingleRootUser (package:busslina_dart_postgresql_lib/core/modules/security/security.module.dart:41)
```

```dart
/// If [doReset] is true it will reset the cache at build time.
  CachedSerializableValueController<T>
      cachedSerializableValue<T extends Object>(
    Option<T> initial, {
    bool doReset = false,
  }) {
    // final (getValue, setValue) =
    //     use.rawValueWrapper<T?>(() => initial.asNullable());
    final value = use.data<T?>(initial.asNullable());
    // final (getVersion, setVersion) =
    //     use.rawValueWrapper(() => initial.isNone ? -1 : 0);
    final version = use.data(initial.isNone ? -1 : 0);

    final rebuild = use.rebuilder();

    bool reset({required bool rebuildMode}) {
      // if (getVersion() == 0) {
      if (version.value == 0) {
        return false;
      }

      // setVersion(initial.isNone ? -1 : 0);
      version.value = initial.isNone ? -1 : 0;
      // setValue(initial.asNullable());
      value.value = initial.asNullable();

      if (rebuildMode) {
        rebuild();
      }

      return true;
    }

    final ctrl = CachedSerializableValueController<T>(
      // getValue: getValue,
      getValue: value.get,
      getVersion: version.get,
      fresh: (freshValue) {
        rebuild((cancel) {
          // if (getVersion() == 0 && getValue() == freshValue) {
          if (version.value == 0 && value.value == freshValue) {
            return cancel();
          }

          // setVersion(0);
          version.value = 0;
          // setValue(freshValue);
          value.value = freshValue;
        });
      },
      set: (newValue, newVersion) {
        // if (newVersion <= getVersion()) {
        if (newVersion <= version.value) {
          return false;
        }

        rebuild((_) {
          // setVersion(newVersion);
          version.value = newVersion;
          // setValue(newValue);
          value.value = newValue;
        });

        return true;
      },
      setIncremental: (newValue) {
        rebuild((_) {
          // setVersion(getVersion() + 1);
          version.value = version.value + 1;
          // version.value++;
          // setValue(newValue);
          value.value = newValue;
        });

        return true;
      },
      setVersionedValue: (versionedValue) {
        // if (versionedValue.version <= getVersion()) {
        if (versionedValue.version <= version.value) {
          return false;
        }

        rebuild((_) {
          // setVersion(versionedValue.version);
          version.value = versionedValue.version;
          // setValue(versionedValue.value as T);
          value.value = versionedValue.value as T;
        });

        return true;
      },
      setVersionedValueDef: (vesionedValueDef) {
        // if (vesionedValueDef.version <= getVersion()) {
        if (vesionedValueDef.version <= version.value) {
          return false;
        }

        rebuild((_) {
          // setVersion(vesionedValueDef.version);
          version.value = vesionedValueDef.version;
          // setValue(vesionedValueDef.value);
          value.value = vesionedValueDef.value;
        });

        return true;
      },
      reset: () => reset(rebuildMode: true),
      // modified: () => getVersion() != 0,
      modified: () => version.value != 0,
    );

    // Conditionally reset
    if (doReset) {
      reset(rebuildMode: false);
    }

    return ctrl;
  }
```

`busslina_dart_lightweight_lib/core/extensions/side_effects.rearch.extension.dart:51` corresponds to `rebuild((cancel) {...` (see `fresh`)

**Comment by GregoryConrad** [comment]
Looks like it’s because you call rebuild (value = newValue) within a rebuild callback.

easy fix: swap all instances of “rebuild” with a transaction. You don’t need to worry about canceling rebuilds—the .value setter will cancel them for you in the value doesn’t change.

**Comment by GregoryConrad** [comment]
Also, you can drop the rebuild mode parameter. Just toss the two state updates in a runTxn. Can be called inside or outside of build.

as an aside, I wonder how hard a rebuild called in rebuild assert would be. Would be more helpful than the current concurrent modification error

**Comment by GregoryConrad** [comment]
Also, now that use.data is a thing, you should basically _never_ have a call to rebuild in your code.

**Comment by busslina** [comment]
> Also, now that use.data is a thing, you should basically never have a call to rebuild in your code anymore.

Of course, my bad. Just realized that before reading your last comment.

**Comment by GregoryConrad** [comment]
Haha no worries! I don’t think I documented that anywhere. I wasn’t even sure myself rebuild in rebuild would cause issues, but figured that concurrency error was possible through some specific scenario

**Comment by busslina** [comment]
Now works fine. This new `data` feature simplifies the code. Good job. Congrats ;)

**Comment by GregoryConrad** [comment]
Glad to hear you like it!
